export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const GET_ACCOUNTS_BEGIN = "GET_ACCOUNTS_BEGIN";
export const GET_ACCOUNTS_SUCCESS = "GET_ACCOUNTS_SUCCESS";

export const SET_EDIT_ACCOUNT = "SET_EDIT_ACCOUNT";

export const SET_DETAIL_ACCOUNT = "SET_DETAIL_ACCOUNT";

export const DELETE_ACCOUNT_BEGIN = "DELETE_ACCOUNT_BEGIN";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_ERROR = "DELETE_ACCOUNT_ERROR";

export const EDIT_ACCOUNT_BEGIN = "EDIT_ACCOUNT_BEGIN";
export const EDIT_ACCOUNT_SUCCESS = "EDIT_ACCOUNT_SUCCESS";
export const EDIT_ACCOUNT_ERROR = "EDIT_ACCOUNT_ERROR";

export const CHANG_PAGE = "CHANGE_PAGE";
